<?php
// This file was generated on 2011-02-06 01:19

$extensionPath = t3lib_extMgm::extPath('egovapi');
$classPath = $extensionPath . 'Classes/';

return array(
	'tx_egovapi_dao_cache' => $classPath . 'Dao/Cache.php',
	'tx_egovapi_dao_dao' => $classPath . 'Dao/Dao.php',
	'tx_egovapi_dao_webservice' => $classPath . 'Dao/WebService.php',
	'tx_egovapi_domain_model_abstractentity' => $classPath . 'Domain/Model/AbstractEntity.php',
	'tx_egovapi_domain_model_audience' => $classPath . 'Domain/Model/Audience.php',
	'tx_egovapi_domain_model_community' => $classPath . 'Domain/Model/Community.php',
	'tx_egovapi_domain_model_domain' => $classPath . 'Domain/Model/Domain.php',
	'tx_egovapi_domain_model_organization' => $classPath . 'Domain/Model/Organization.php',
	'tx_egovapi_domain_model_service' => $classPath . 'Domain/Model/Service.php',
	'tx_egovapi_domain_model_topic' => $classPath . 'Domain/Model/Topic.php',
	'tx_egovapi_domain_model_view' => $classPath . 'Domain/Model/View.php',
	'tx_egovapi_domain_model_block_approval' => $classPath . 'Domain/Model/Block/Approval.php',
	'tx_egovapi_domain_model_block_contact' => $classPath . 'Domain/Model/Block/Contact.php',
	'tx_egovapi_domain_model_block_descriptor' => $classPath . 'Domain/Model/Block/Descriptor.php',
	'tx_egovapi_domain_model_block_document' => $classPath . 'Domain/Model/Block/Document.php',
	'tx_egovapi_domain_model_block_documentsother' => $classPath . 'Domain/Model/Block/DocumentsOther.php',
	'tx_egovapi_domain_model_block_documentsrequired' => $classPath . 'Domain/Model/Block/DocumentsRequired.php',
	'tx_egovapi_domain_model_block_fee' => $classPath . 'Domain/Model/Block/Fee.php',
	'tx_egovapi_domain_model_block_form' => $classPath . 'Domain/Model/Block/Form.php',
	'tx_egovapi_domain_model_block_forms' => $classPath . 'Domain/Model/Block/Forms.php',
	'tx_egovapi_domain_model_block_generalinformation' => $classPath . 'Domain/Model/Block/GeneralInformation.php',
	'tx_egovapi_domain_model_block_legalregulation' => $classPath . 'Domain/Model/Block/LegalRegulation.php',
	'tx_egovapi_domain_model_block_legalregulationitem' => $classPath . 'Domain/Model/Block/LegalRegulationItem.php',
	'tx_egovapi_domain_model_block_news' => $classPath . 'Domain/Model/Block/News.php',
	'tx_egovapi_domain_model_block_prerequisite' => $classPath . 'Domain/Model/Block/Prerequisite.php',
	'tx_egovapi_domain_model_block_prerequisites' => $classPath . 'Domain/Model/Block/Prerequisites.php',
	'tx_egovapi_domain_model_block_procedure' => $classPath . 'Domain/Model/Block/Procedure.php',
	'tx_egovapi_domain_model_block_procedureitem' => $classPath . 'Domain/Model/Block/ProcedureItem.php',
	'tx_egovapi_domain_model_block_remarks' => $classPath . 'Domain/Model/Block/Remarks.php',
	'tx_egovapi_domain_model_block_serviceprovided' => $classPath . 'Domain/Model/Block/ServiceProvided.php',
	'tx_egovapi_domain_model_block_subdomain' => $classPath . 'Domain/Model/Block/Subdomain.php',
	'tx_egovapi_domain_model_block_subdomains' => $classPath . 'Domain/Model/Block/Subdomains.php',
	'tx_egovapi_domain_model_block_subtopic' => $classPath . 'Domain/Model/Block/Subtopic.php',
	'tx_egovapi_domain_model_block_subtopics' => $classPath . 'Domain/Model/Block/Subtopics.php',
	'tx_egovapi_domain_model_block_synonym' => $classPath . 'Domain/Model/Block/Synonym.php',
	'tx_egovapi_domain_repository_abstractrepository' => $classPath . 'Domain/Repository/AbstractRepository.php',
	'tx_egovapi_domain_repository_audiencerepository' => $classPath . 'Domain/Repository/AudienceRepository.php',
	'tx_egovapi_domain_repository_communityrepository' => $classPath . 'Domain/Repository/CommunityRepository.php',
	'tx_egovapi_domain_repository_domainrepository' => $classPath . 'Domain/Repository/DomainRepository.php',
	'tx_egovapi_domain_repository_factory' => $classPath . 'Domain/Repository/Factory.php',
	'tx_egovapi_domain_repository_organizationrepository' => $classPath . 'Domain/Repository/OrganizationRepository.php',
	'tx_egovapi_domain_repository_servicerepository' => $classPath . 'Domain/Repository/ServiceRepository.php',
	'tx_egovapi_domain_repository_topicrepository' => $classPath . 'Domain/Repository/TopicRepository.php',
	'tx_egovapi_domain_repository_viewrepository' => $classPath . 'Domain/Repository/ViewRepository.php',
	'tx_egovapi_utility_flexform' => $classPath . 'Utility/FlexForm.php',
	'tx_egovapi_utility_objects' => $classPath . 'Utility/Objects.php',
	'tx_egovapi_utility_ts' => $classPath . 'Utility/TypoScript.php',
	'tx_egovapi_controller_pi1_abstractrenderer' => $classPath . 'Controller/Pi1/AbstractRenderer.php',
	'tx_egovapi_controller_pi1_fluidrenderer' => $classPath . 'Controller/Pi1/FluidRenderer.php',
	'tx_egovapi_controller_pi1_templaterenderer' => $classPath . 'Controller/Pi1/TemplateRenderer.php',
	'tx_egovapi_interfaces_template_audiencehook' => $extensionPath . 'Interfaces/Template/AudienceHook.php',
	'tx_egovapi_interfaces_template_domainhook' => $extensionPath . 'Interfaces/Template/DomainHook.php',
	'tx_egovapi_interfaces_template_renderhook' => $extensionPath . 'Interfaces/Template/RenderHook.php',
	'tx_egovapi_interfaces_template_servicehook' => $extensionPath . 'Interfaces/Template/ServiceHook.php',
	'tx_egovapi_interfaces_template_topichook' => $extensionPath . 'Interfaces/Template/TopicHook.php',
	'tx_egovapi_interfaces_template_viewhook' => $extensionPath . 'Interfaces/Template/ViewHook.php',
);
?>